packages:
    - "modules/*"
    - "packages/testing/*"
    - "packages/shared/*"
    - "packages/bridge"
    - "packages/cli"
    - "packages/config"
    - "packages/core"
    - "packages/env"
    - "packages/signer_service"
