export enum AssertionErrors {
    CHAIN_TYPE_MISMATCH = "CHAIN_TYPE_MISMATCH",
    CHAIN_ENVIRONMENT_MISMATCH = "CHAIN_ENVIRONMENT_MISMATCH",
    UNKNOWN_CUSTOM_ERROR = "execution reverted (unknown custom error)",
    TRANSACTION_SUBMISSION_FAILED = "TRANSACTION_SUBMISSION_FAILED",
}
