export enum AssertionErrors {
    CHAIN_TYPE_MISMATCH = "CHAIN_TYPE_MISMATCH",
    CHAIN_ENVIRONMENT_MISMATCH = "CHAIN_ENVIRONMENT_MISMATCH",
    GATEWAY_BALANCE_LESS_THAN_TOTAL_SUPPLY = "GATEWAY_BALANCE_LESS_THAN_TOTAL_SUPPLY",
}
