export enum AxelarScanProviderErrors {
    LOCALNET_NOT_SUPPORTED = "LOCALNET_NOT_SUPPORTED",
    UNKNOWN_ENVIRONMENT = "UNKNOWN_ENVIRONMENT",
    TRANSACTION_EXECUTION_FAILED = "TRANSACTION_EXECUTION_FAILED",
    INVALID_TRANSFER_AMOUNT = "invalid transfer amount",
    INSUFFICIENT_FEE = "Insufficient fee",
    INVALID_DESTINATION_ADDRESS = "invalid destination address",
    TOKEN_ALREADY_DEPLOYED = "already deployed",
}
