name: build-base

on:
    workflow_call:
        inputs:
            tag:
                required: true
                type: string
            push:
                required: true
                type: boolean

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - name: Repository checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # Configure tag name
            - name: Sets env vars
              run: |
                  echo "DOCKER_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}" >> $GITHUB_ENV

            # Build docker image
            - name: Build docker image
              uses: docker/build-push-action@v4
              with:
                  file: Dockerfile
                  push: ${{ inputs.push }}
                  tags: ${{ inputs.tag }}
