name: "Push main"

on:
    push:
        branches:
            - main

concurrency:
    # Cancel old runs if there is a new commit in the same branch
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-docker:
        uses: ./.github/workflows/build-docker.yml
        secrets: inherit
        with:
            tag: ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
            push: true