name: "Pull Request"

on:
    pull_request:
        types: [opened, synchronize]

concurrency:
    # Cancel old runs if there is a new commit in the same branch
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build-cosmos:
        uses: ./.github/workflows/build-cosmos.yml
        secrets: inherit
    build-evm:
        uses: ./.github/workflows/build-evm.yml
        secrets: inherit
        with:
            target: integration
            push: false
    build-axelar:
        uses: ./.github/workflows/build-axelar.yml
        secrets: inherit
        with:
            target: integration
            push: false
